[package]
name = "camden"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3.2"
indicatif = "0.17.3"
twox-hash = "1.6.0"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"